//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Catch
    {
        public Catch()
        {
            this.FishingSession = new HashSet<FishingSession>();
        }
    
        public int cId { get; set; }
        [DisplayName("Weight of catch")]
        [Required(ErrorMessage = "Weight is necessary")]
        public decimal weight { get; set; }
       
        [DisplayName("Weight of lure")]
        [Required(ErrorMessage = "Weight is necessary")]
        public int lureweight { get; set; }
       
        [DisplayName("Depth")]
        [Required(ErrorMessage = "Depth is necessary")]
        public int depth { get; set; }
       
        [DisplayName("Description of catch")]
        [Required(ErrorMessage = "Description is necessary")]
        [StringLength(200)]
        public string description { get; set; }
       
        [DisplayName("Lure")]
        [Required(ErrorMessage = "Lure is necessary")]
        public int lId { get; set; }
      
        [DisplayName("Fish species")]
        [Required(ErrorMessage = "Species is necessary")]
        public int fiId { get; set; }
    
        public virtual FishSpecies FishSpecies { get; set; }
        public virtual Lure Lure { get; set; }
        public virtual ICollection<FishingSession> FishingSession { get; set; }
    }
}
