//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class FishingSession
    {
        public FishingSession()
        {
            this.Catch = new HashSet<Catch>();
        }
    
        public int fsId { get; set; }

        [Required(ErrorMessage = "Date is required")]
        [DisplayName("Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy}")]
        [DataType(DataType.DateTime)]
        public System.DateTime date { get; set; }

        [DisplayName("Session description")]
        [StringLength(200)]
        public string description { get; set; }

        public int fId { get; set; }

        [DisplayName("Fishing Method")]
        public int fmId { get; set; }

        [DisplayName("Location")]
        public int lmId { get; set; }
    
        public virtual Fisherman Fisherman { get; set; }
        public virtual FishingMethod FishingMethod { get; set; }
        public virtual LocationMarking LocationMarking { get; set; }
        public virtual ICollection<Catch> Catch { get; set; }
    }
}
