//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishingSession
    {
        public int fsId { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
        public int fId { get; set; }
        public int fmId { get; set; }
        public int cId { get; set; }
        public int lmId { get; set; }
    
        public virtual Catch Catch { get; set; }
        public virtual Fisherman Fisherman { get; set; }
        public virtual FishingMethod FishingMethod { get; set; }
        public virtual LocationMarking LocationMarking { get; set; }
    }
}
