//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fisherman
    {
        public Fisherman()
        {
            this.FishingSession = new HashSet<FishingSession>();
        }
    
        public int fId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phone { get; set; }
        public string eMail { get; set; }
        public string gender { get; set; }
        public string passwordHashFields { get; set; }
    
        public virtual ICollection<FishingSession> FishingSession { get; set; }
    }
}
