//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class FishingMethod
    {
        public FishingMethod()
        {
            this.FishingSession = new HashSet<FishingSession>();
        }
    
        public int fmId { get; set; }

        [Required(ErrorMessage = "Method name is required.")]
        [DisplayName("Fishing method")]
        [Remote("CheckMethodName", "Validation", AdditionalFields = "fmId", ErrorMessage = "This fishing method name is already used.")]
        [StringLength(100)]
        public string methodname { get; set; }

        [DisplayName("Description")]
        [StringLength(200)]
        public string description { get; set; }
    
        public virtual ICollection<FishingSession> FishingSession { get; set; }
    }
}
