//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishSpecies
    {
        public FishSpecies()
        {
            this.Catch = new HashSet<Catch>();
        }
    
        public int fiId { get; set; }
        public string fishname { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Catch> Catch { get; set; }
    }
}
