//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class FishSpecies
    {
        public FishSpecies()
        {
            this.Catch = new HashSet<Catch>();
        }

        public int fiId { get; set; }

        [Required(ErrorMessage = "Fish name is necessary")]
        [DisplayName("Fish species")]
        [Remote("CheckFishName", "Validation", AdditionalFields = "fiId", ErrorMessage = "This fish name is already taken.")]
        [StringLength(100)]
        public string fishname { get; set; }

        [DisplayName("Species description")]
        [StringLength(200)]
        public string description { get; set; }
        

        public virtual ICollection<Catch> Catch { get; set; }
       
    }
}
