//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishingMethod
    {
        public FishingMethod()
        {
            this.FishingSession = new HashSet<FishingSession>();
        }
    
        public int fmId { get; set; }
        public string methodname { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<FishingSession> FishingSession { get; set; }
    }
}
