//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class GeoCoordinates
    {
        public GeoCoordinates()
        {
            this.LocationMarking = new HashSet<LocationMarking>();
        }

        [DisplayName("Id")]
        public int gcId { get; set; }

        [DisplayName("Latitude")]
        [Required(ErrorMessage = "Please enter latitude.")]
        public decimal latitude { get; set; }

        [DisplayName("Longitude")]
        [Required(ErrorMessage = "Please enter longitude.")]
        public decimal longitude { get; set; }
    
        public virtual ICollection<LocationMarking> LocationMarking { get; set; }
    }
}
