//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationMarking
    {
        public LocationMarking()
        {
            this.FishingSession = new HashSet<FishingSession>();
        }
    
        public int lmId { get; set; }
        public string sublocation { get; set; }
        public string compaslocation { get; set; }
        public string description { get; set; }
        public int wId { get; set; }
        public Nullable<int> gcId { get; set; }
    
        public virtual ICollection<FishingSession> FishingSession { get; set; }
        public virtual GeoCoordinates GeoCoordinates { get; set; }
        public virtual Water Water { get; set; }
    }
}
