//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LureType
    {
        public LureType()
        {
            this.Lure = new HashSet<Lure>();
        }
    
        public int ltId { get; set; }
        public string typename { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Lure> Lure { get; set; }
    }
}
