//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class LureType
    {
        public LureType()
        {
            this.Lure = new HashSet<Lure>();
        }

        public int ltId { get; set; }

        [Required(ErrorMessage = "Lure type name is necessary")]
        [DisplayName("Lure type name")]
        [Remote("CheckLureTypeName", "Validation", AdditionalFields = "ltId", ErrorMessage = "This lure type name is already taken.")]
        [StringLength(100)]
        public string typename { get; set; }

        [Required(ErrorMessage = "Description is necessary")]
        [DisplayName("Description of lure type")]
        [StringLength(200)]
        public string description { get; set; }
    
        public virtual ICollection<Lure> Lure { get; set; }
    }
}
