//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FishermanDBEntities : DbContext
    {
        public FishermanDBEntities()
            : base("name=FishermanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Catch> Catch { get; set; }
        public DbSet<Fisherman> Fisherman { get; set; }
        public DbSet<FishingMethod> FishingMethod { get; set; }
        public DbSet<FishingSession> FishingSession { get; set; }
        public DbSet<FishSpecies> FishSpecies { get; set; }
        public DbSet<GeoCoordinates> GeoCoordinates { get; set; }
        public DbSet<LocationMarking> LocationMarking { get; set; }
        public DbSet<Lure> Lure { get; set; }
        public DbSet<LureType> LureType { get; set; }
        public DbSet<Water> Water { get; set; }
    }
}
