//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForTheFisherman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Water
    {
        public Water()
        {
            this.LocationMarking = new HashSet<LocationMarking>();
        }
    
        public int wId { get; set; }
        public string name { get; set; }
        public string municipality { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<LocationMarking> LocationMarking { get; set; }
    }
}
